### ISSUE TITLE
Dark Mode color property always applied

### ISSUE THREAD

**Issue by rcoundon** [formkit/themes.formkit.com#4]
Mac OS 14.4 (23E214)

If the system appearance setting is set to Dark, when generating a theme the media query:

```css
@media (prefers-color-scheme: dark)
.dark\:text-neutral-300 {
    --tw-text-opacity: 1;
    color: rgb(212 212 212 / var(--tw-text-opacity));
}
```

Is always applied. This makes the text appear a very light grey on a white background.

<img width="418" alt="image" src="https://github.com/formkit/themes.formkit.com/assets/9136570/898e47cf-f502-4de5-bd88-ece69fbaba68">

Setting the system appearance to Light sets the color correctly as the media query is not applied:

<img width="403" alt="image" src="https://github.com/formkit/themes.formkit.com/assets/9136570/5a3f0092-1289-4099-bde2-56ac7535c17c">

Another way of putting this would be that, if the form is not implementing a dark mode but the user has set this as a preference, the text changes colour anyway. So maybe the real question is, what is the proper way to disable dark mode support in a theme?
